version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: landcla_backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - BACKEND_DB_PATH=/app/shared_memory.db
      - BACKEND_UPLOAD_DIR=/app/temp_uploads
    volumes:
      - ./backend/shared_memory.db:/app/shared_memory.db
      - ./backend/temp_uploads:/app/temp_uploads
    restart: unless-stopped

  frontend:
    build:
      context: ./land-classification-frontend
      dockerfile: Dockerfile
    container_name: landcla_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://34.61.126.255:8000
    depends_on:
      - backend
    restart: unless-stopped
